### ISSUE TITLE
Windows Installation failure 

### ISSUE THREAD

**Issue by rwbaer** [js229/Vennerable#41]
Installation attempt on Windows 10 fails:

The problem seems either due to the fact that R is on a drive drive E:\ or more likely that it is located in a directory containing a space in its name:  E:\Program Files\R\R-3.3.2  The problem is either way, I don't know how to work around it.

```
> install_github("js229/Vennerable");
Downloading GitHub repo js229/Vennerable@master
from URL https://api.github.com/repos/js229/Vennerable/zipball/master
Installing Vennerable
"E:/Program Files/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL "C:/Users/Rob  \
  Baer/AppData/Local/Temp/RtmpmOnZXW/devtools828ded11e9/js229-Vennerable-46057c9"  \
  --library="C:/Users/Rob Baer/R/win-library/3.3" --install-tests 

'E:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
Called from: fun(r, args = args, env_vars = env_vars, path = path, ...)

```

**Comment by js229** [comment]
I very much doubt this is a problem with Vennerable.

A fresh install of R 3.3.2 , running in Rstudio 1.0.44, and the six (sorry) separate commands listed at https://github.com/js229/Vennerable/blob/master/README.md works fine for me (though a couple of extra packages, plyr and stringr need downloading too):

```

> install_github("js229/Vennerable",force=TRUE);
Downloading GitHub repo js229/Vennerable@master
from URL https://api.github.com/repos/js229/Vennerable/zipball/master
Installing Vennerable
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Jonathan/AppData/Local/Temp/RtmpoNzFuU/devtools156c33015d1e/js229-Vennerable-46057c9"  \
  --library="C:/Users/Jonathan/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'Vennerable' ...
```

**Comment by rwbaer** [comment]
Well, I just got around to trying again, with devtools, and I guess the issue is that something in the tool chain can't handle paths with spaces in it.

> library(devtools)
> install_github("js229/Vennerable"); library(Vennerable)
Downloading GitHub repo js229/Vennerable@master
from URL https://api.github.com/repos/js229/Vennerable/zipball/master
Installing Vennerable
"E:/Program Files/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Rob  \
  Baer/AppData/Local/Temp/RtmpS8b8S4/devtools2458420a5ed3/js229-Vennerable-46057c9" --library="C:/Users/Rob Baer/R/win-library/3.3"  \
  --install-tests 

'E:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)

The problem is likely the space in my user name and thus my home directory.  Don't know the workaround.

**Comment by js229** [comment]
Well, looks like a difference in install_github between your system and mine then. I suggest you see if you can use install_github on a different R package (don't know of one, sorry) and consult the install_github maintainer with the results.

**Comment by rwbaer** [comment]
I have left this alone for too long, but with the current bioconductor and devtools all works as expected.  Closing.
